services:
  api1: &api
    build: .
    hostname: api1
    depends_on:
      - db
      - redis
    environment:
      - PORT=8080
      - DB_URL=jdbc:postgresql://localhost:5432/rinha_db
      - DB_USERNAME=rinha
      - DB_PASSWORD=rinha
      - REDIS_HOST=localhost
      - REDIS_PORT=6379
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: '0.52'
          memory: '0.65GB'

  api2:
    <<: *api
    hostname: api2
    environment:
      - PORT=8081
      - DB_URL=jdbc:postgresql://localhost:5432/rinha_db
      - DB_USERNAME=rinha
      - DB_PASSWORD=rinha
      - REDIS_HOST=localhost
      - REDIS_PORT=6379

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: '0.05'
          memory: '500MB'

  db:
    image: postgres
    restart: always
    hostname: db
    environment:
      POSTGRES_USER: rinha
      POSTGRES_PASSWORD: rinha
      POSTGRES_DB: rinha_db
    volumes:
      - ./postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
    ports:
      - '5432:5432'
    command: postgres -c config_file=/docker-entrypoint-initdb.d/postgresql.conf
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '1.1GB'

  redis:
    image: redis
    hostname: redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save "" --appendonly no --maxclients 20000
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: '0.01'
          memory: '100MB'