worker_processes auto;

events {
    worker_connections 20480;
}
http {
    upstream api {
        server localhost:8080;
        server localhost:8081;
        keepalive 500;
    }

    server {
        listen 9999;
        location / {
            proxy_pass http://api;
        }
    }
}