POST http://localhost:8080/pessoas HTTP/1.1
content-type: application/json

{
    "apelido" : "josé",
    "nome" : "José Roberto",
    "nascimento" : "2000-10-01",
    "stack" : ["C#", "Node", "Oracle"]
}

###
GET http://localhost:8080/pessoas?t=node HTTP/1.1
content-type: application/json

### 
GET http://localhost:8080/pessoas/b54a6952-51a6-41bf-8ae9-94e4b6b99761 HTTP/1.1
content-type: application/json